from src.main.depends import container

url = 'https://checkout.stripe.com/c/pay/cs_live_b1pYe4yZJVn3xdd0eJNk7YQLVj1WNQQtSL9XFjTYuvBLaMIfxbWLyS3zZx#fidkdWxOYHwnPyd1blppbHNgWjA0SXJiPUtPS000NlRnbnJwfWJSVUBiMTVhYHFdMVUyMVZjczUwVG11aGldNlB1dzE1bEBiXF89YGBCbkJEX09udm1VT3dMPU9qaGFnQjBqTTJoY0NONVU2NTVEMFZLMn09fCcpJ2hsYXYnP34naHBsYSc%2FJ2cwNGc8NmdhKGEwMTMoMWM9MihkMTFnKGdjNTU3MTQ9NTNnMDBkNzU9ZCcpJ3ZsYSc%2FJz03YTVjNDM9KGdkNGMoMWcyZCg8ZmFkKGBkYTJhNDM9YTM2Y2NmNzY3MicpJ2JwbGEnPyc1PWRhZjxmZChjNmQxKDFkM2AoZz00MSgxNjEzZGdnNmQ1MGY9NTMzNjwneCknZ2BxZHYnP15YKSdpZHxqcHFRfHVgJz8naHBpcWxabHFgaCcpJ3dgY2B3d2B3SndsYmxrJz8nbXFxdXY%2FKipkdXUraWBqa2R3YWorZGwneCUl'
r = container.get_stripe_payment_data_from_url_use_case()(
    url=url
)
print(r)
